plugins {
    id 'java'
    id 'application'
}

group = 'com.exercicios'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'mysql:mysql-connector-java:8.0.33'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

application {
    mainClass = 'com.exercicios.Questao2'
}

tasks.register('runQuestao1', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.exercicios.Questao1'
}

tasks.register('runQuestao2', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.exercicios.Questao2'
}
